Add filter by maximized window
psifidotos/applet-window-title pull request #139
Opened 2022-08-15 22:42 UTC by sr-tream

Add filter to be able to show info only for maximized windows.

![settings screenshot](https://user-images.githubusercontent.com/12231048/184732997-ab725740-88ce-4ebd-becb-16cc1e595caa.png)

2022-12-04 21:20 UTC, amorozov requested changes
In the pure Plasma (=not Latte) environment it behaves exactly as I expected:

when a window is not maximized, activity information or fallback is displayed.

Maybe the only suggestion is to preserve space when activity information is **not** shown and fallback is empty. That way the applets right of the window-title applet would preserve their positions when the active window is maximized/unmaximized.

Also the text of the label in the config/main.xml needs minor adjustment.

2022-12-04 21:20 UTC, amorozov commented on contents/config/main.xml
> +    <label>If true it only shows the app menu if the current active window is maximized</label>
Likely, not "app menu" but "app title"

2022-12-05 11:06 UTC, sr-tream commented
@amorozov 
> Maybe the only suggestion is to preserve space when activity information is not shown and fallback is empty.

It must work without my PR, like when no any windows present (e.g. after new session started)

2023-02-22 19:07 UTC, jetthusher approved these changes

2023-02-24 23:47 UTC, amorozov approved these changes
works for me

2026-08-02 08:52 UTC, closed without merging